# Generated by Django 2.1.2 on 2019-07-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogs',
            name='Branch_Comp_Dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.TblBranchCompDept'),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='internet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.TblInternet'),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.TblJobTitle'),
        ),
    ]
