# Generated by Django 2.1.2 on 2019-07-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20190710_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogs',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='internet',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='jabber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='network',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='remarks',
            field=models.TextField(default='New Account', null=True),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='work_order',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
