# Generated by Django 2.1.2 on 2019-07-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_auto_20190710_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogs',
            name='jabber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
