# Generated by Django 2.1.2 on 2019-07-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20190710_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogs',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
