# Generated by Django 2.1.2 on 2019-07-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20190710_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogs',
            name='jabber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='createlogs',
            name='network',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
