# Generated by Django 2.1.2 on 2019-07-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_auto_20190710_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlogs',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
